// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJBAKmeSB722xxxN_EXX-DJ7FLmMt1qN0',
    appId: '1:1015212971215:web:228e9f59ecc9cb862213ba',
    messagingSenderId: '1015212971215',
    projectId: 'flyin-79b30',
    authDomain: 'flyin-79b30.firebaseapp.com',
    storageBucket: 'flyin-79b30.appspot.com',
    measurementId: 'G-JT5XP4ZX8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLdXbwWVuV5qhtu4T6nxUOhPvUFMEByLU',
    appId: '1:1015212971215:android:270113a71035f8a32213ba',
    messagingSenderId: '1015212971215',
    projectId: 'flyin-79b30',
    storageBucket: 'flyin-79b30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1COeNL5SSZihat27nW_dWukSwZTgy43s',
    appId: '1:1015212971215:ios:25ebd1cc810d95df2213ba',
    messagingSenderId: '1015212971215',
    projectId: 'flyin-79b30',
    storageBucket: 'flyin-79b30.appspot.com',
    iosBundleId: 'com.example.flyin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1COeNL5SSZihat27nW_dWukSwZTgy43s',
    appId: '1:1015212971215:ios:e3a2a1cac3489af82213ba',
    messagingSenderId: '1015212971215',
    projectId: 'flyin-79b30',
    storageBucket: 'flyin-79b30.appspot.com',
    iosBundleId: 'com.example.flyin.RunnerTests',
  );
}
